### ISSUE TITLE
Not working for angular tags <ng-component>

### ISSUE THREAD

**Issue by kamil-kielczewski** [formulahendry/vscode-auto-rename-tag#38] opened 2017-11-16 09:33 UTC
Not working for angular tag e.g.:

`<ng-component></ng-component>`

It should work for any kinds of tags

**Comment by formulahendry** [comment] 2017-11-17 07:44
Could not reproduce on my side.
Do you try with different tags?

**Comment by kamil-kielczewski** [comment] 2017-11-17 11:39
HTML tags works (like for example <div>) but no-HTML tag-s doesn't work :(

**Comment by kamil-kielczewski** [comment] 2017-11-17 11:50
This is list of my plugins:
https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
https://marketplace.visualstudio.com/items?itemName=jakethashi.vscode-angular2-emmet
https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify
https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account
https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker

thats all - i think that first three can have conflict.

**Comment by formulahendry** [comment] 2017-11-17 12:10
Could you disable all other extension and try again?

**Comment by kamil-kielczewski** [comment] 2017-11-17 12:42
hm strange - i disable all - and then it starts to work. But when I enble other plugins again, the bug not appear and everything works good :) (may be my behaviour change sequence of plugins starting in VSCode?)

**Comment by formulahendry** [comment] 2017-11-17 13:00
Good to know it is working. Closing it then.

**Closed by formulahendry** 2017-11-17 13:00 UTC
Labels: need more info
